version: '3.8'
services:
  game-lending:
    build:
      context: .
      dockerfile: src/GameLending.HttpApi.Host/Dockerfile
    depends_on:
      - redis
      - sqlserver
      - identity-service
  identity-service:
    build:
      context: .
      dockerfile: src/GameLending.IdentityServer/Dockerfile
    depends_on:
      - redis
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports: 
      - "11433:1433"
    environment:
        SA_PASSWORD: "@dminX123"
        ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/var/opt/mssql
  redis:
    image: "redis:alpine"
    
volumes:
  dbdata: